In [2]:
!pip3 install torch
!pip3 install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [65]:
import numpy as np
import torch

# 텐서 초기화와 데이터 타입


초기화 되지 않는 텐서

In [10]:
x = torch.empty(4,2) # (row, col)
print(x)

tensor([[6.6464e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 1.5554e-43],
        [1.1578e+27, 1.1362e+30]])


무작위로 초기화된 텐서

In [11]:
x = torch.rand(4,2)
print(x)

tensor([[0.8778, 0.0292],
        [0.4999, 0.2883],
        [0.8830, 0.0241],
        [0.8486, 0.8955]])


데이터 타입이 long이고, 0으로 채워진 텐서

In [12]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [13]:
x = torch.tensor([3, 33,33])
print(x)

tensor([ 3, 33, 33])


2 x 4크기, double type 1로 채워진 텐서


In [16]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


x와 같은 크기, float 타입, 무작위로 채워진 텐서
- rand_like 사용

In [18]:
x = torch.rand_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[0.2886, 0.9394, 0.8547, 0.8915],
        [0.7576, 0.8937, 0.5747, 0.4839]])
torch.Size([2, 4])


Data Type

In [23]:
ft = torch.FloatTensor([1,2,3])
print(ft, ft.dtype)

print(ft.short())
print(ft.int())
print(ft.long())

it = torch.IntTensor([1,2,3])
print(it, it.dtype)
print(it.float())
print(it.double())

tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.int32) torch.int32
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


CUDA Tensors
- .to 메소드를 사용하여 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있음

In [7]:
x = torch.rand([2,4])
print(x, x.dtype)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

y = torch.ones_like(x, device=device)
print(y, y.dtype)

x = x.to(device)
print(x)

z = x + y
print(z)

print(z.to('cpu', torch.double))

tensor([[0.6807, 0.8777, 0.9507, 0.3137],
        [0.6663, 0.4543, 0.0970, 0.9805]]) torch.float32
cuda
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0') torch.float32
tensor([[0.6807, 0.8777, 0.9507, 0.3137],
        [0.6663, 0.4543, 0.0970, 0.9805]], device='cuda:0')
tensor([[1.6807, 1.8777, 1.9507, 1.3137],
        [1.6663, 1.4543, 1.0970, 1.9805]], device='cuda:0')
tensor([[1.6807, 1.8777, 1.9507, 1.3137],
        [1.6663, 1.4543, 1.0970, 1.9805]], dtype=torch.float64)


0D Tensor(Scalar)
- 하나의 숫자를 담고 있는 텐서
- 축과 형상이 없음

In [8]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


1D Tensor(Vector)

- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축 존재

In [9]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


2D Tensor(Matrix)

- 행렬과 같은 모양으로 두개의 축이 존재
- 일반적으인 수치, 통계 데이터 셋이 해당
- 주로 Sample과 Features를 가진 구조로 사용

In [10]:
t2 = torch.tensor([[1,2,3], [4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


텐서의 연산

In [16]:
import math

a = torch.rand(1, 2) * 2 -1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[0.2417, 0.7622]])
tensor([[0.2417, 0.7622]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.2417, 0.5000]])


In [17]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,1,1,2,2,2])))

tensor([[0.2417, 0.7622]])
tensor(0.2417)
tensor(0.7622)
tensor(0.5019)
tensor(0.3680)
tensor(0.1842)
tensor([1, 2, 3])


In [20]:
x = torch.rand(2,2)
print(x)
print(x.max(dim = 0))
print(x.max(dim = 1))

tensor([[0.8496, 0.5825],
        [0.0199, 0.8554]])
torch.return_types.max(
values=tensor([0.8496, 0.8554]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([0.8496, 0.8554]),
indices=tensor([0, 1]))


In [25]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
result = torch.empty(x.shape)
torch.add(x,y, out = result)
print(result)

tensor([[0.7504, 0.3912],
        [0.6940, 0.0818]])
tensor([[0.5885, 0.9497],
        [0.2010, 0.6356]])
tensor([[1.3389, 1.3409],
        [0.8949, 0.7174]])


in-place 방식
- 텐서의 값을 변경하는 연산 뒤에느느 _가 붙음
- x.copy_(y) ..

In [26]:
print(x)
print(y)
y.add_(x) # y와 x를 더한 것을 y에 덮어 쓴다.
print(y)

tensor([[0.7504, 0.3912],
        [0.6940, 0.0818]])
tensor([[0.5885, 0.9497],
        [0.2010, 0.6356]])
tensor([[1.3389, 1.3409],
        [0.8949, 0.7174]])


# 텐서의 조작

인덱싱 : Numpy 처럼 인덱싱 형태로 사용가능

In [36]:
x = torch.Tensor([[1,2],
                 [3,4]])

print(x)
print(x[0][0])
print(x[0, 0])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(1.)
tensor([3., 4.])


view : 텐서의 크기나 모양을 변경
- 기본적으로 변경 전 후에 텐서안의 원소개수가 유지 되야함
- -1로 설정되면 계산을 통해 해당 크기 값을 유추

In [39]:
x = torch.rand(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5, -1)
print(z)

tensor([[0.4694, 0.4391, 0.8815, 0.8074, 0.3181],
        [0.8855, 0.2338, 0.9184, 0.9107, 0.5747],
        [0.1943, 0.1062, 0.3666, 0.4886, 0.7747],
        [0.1071, 0.1742, 0.8412, 0.7230, 0.1521]])
tensor([0.4694, 0.4391, 0.8815, 0.8074, 0.3181, 0.8855, 0.2338, 0.9184, 0.9107,
        0.5747, 0.1943, 0.1062, 0.3666, 0.4886, 0.7747, 0.1071, 0.1742, 0.8412,
        0.7230, 0.1521])
tensor([[0.4694, 0.4391, 0.8815, 0.8074],
        [0.3181, 0.8855, 0.2338, 0.9184],
        [0.9107, 0.5747, 0.1943, 0.1062],
        [0.3666, 0.4886, 0.7747, 0.1071],
        [0.1742, 0.8412, 0.7230, 0.1521]])


item : 텐서에 값이 하나라도 존재하면 굿자 값을 얻을 수 있다
- 스칼라값 하나만 있을떄만 사용할 수 있다.

In [42]:
x = torch.rand(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.2980])
0.29804307222366333
torch.float32


squeeze : 차원을 축소(제거)
- 맨앞이 1차원이라면 차원을 하나 없애도 같은 의미이다.
- 이떄 squeeze를 사용

In [47]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor2 = tensor.squeeze()
print(tensor2)
print(tensor2.shape)

tensor([[[0.6370, 0.4340, 0.7402],
         [0.0898, 0.3826, 0.6457],
         [0.2000, 0.8287, 0.4967]]])
torch.Size([1, 3, 3])
tensor([[0.6370, 0.4340, 0.7402],
        [0.0898, 0.3826, 0.6457],
        [0.2000, 0.8287, 0.4967]])
torch.Size([3, 3])


unsqueeze : 차원을 증가(생성)

In [51]:
tensor = torch.rand(3,3)
print(tensor)
print(tensor.shape)

tensor2 = tensor.unsqueeze(1) # 2번쨰 차원에 대해 1차원을 늘려라. 
print(tensor2)
print(tensor2.shape)

tensor([[0.1813, 0.0262, 0.3447],
        [0.8417, 0.0072, 0.4445],
        [0.3798, 0.6047, 0.4555]])
torch.Size([3, 3])
tensor([[[0.1813, 0.0262, 0.3447]],

        [[0.8417, 0.0072, 0.4445]],

        [[0.3798, 0.6047, 0.4555]]])
torch.Size([3, 1, 3])


stack : 텐서간 결합

In [53]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


cat : 텐서를 결합하는 메소드(concatenate)
- stack과 유사하지만 쌓을 dim이 존재
- 해당 차원을 늘려준 후 결합

In [57]:
a = torch.rand(1,3,3)
b = torch.rand(1,3,3)
print(a, a.shape)
print(b, b.shape)
# c = torch.cat((a,b), dim = 0) # 1번쨰 차원을 기준으로 합친다.
# c = torch.cat((a,b), dim = 1) # 2번쨰 차원을 기준으로 합친다.
c = torch.cat((a,b), dim = 2) # 3번쨰 차원을 기준으로 합친다.
print(c, c.shape)

tensor([[[0.7925, 0.0582, 0.6169],
         [0.9845, 0.6889, 0.4882],
         [0.0800, 0.8313, 0.8273]]]) torch.Size([1, 3, 3])
tensor([[[0.6642, 0.9156, 0.8289],
         [0.8393, 0.9809, 0.2697],
         [0.3134, 0.5982, 0.1592]]]) torch.Size([1, 3, 3])
tensor([[[0.7925, 0.0582, 0.6169, 0.6642, 0.9156, 0.8289],
         [0.9845, 0.6889, 0.4882, 0.8393, 0.9809, 0.2697],
         [0.0800, 0.8313, 0.8273, 0.3134, 0.5982, 0.1592]]]) torch.Size([1, 3, 6])


chunck : 텐서를 여러개로 나눌 떄 사용(몇개로 나눌 것인가?)

In [58]:
tensor = torch.rand(3,6)
print(tensor)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1) # 3개로 2번쨰 차원을 기준으로 나눠줘
print(t1)
print(t2)
print(t3)

tensor([[0.4095, 0.3251, 0.1432, 0.3541, 0.3867, 0.2708],
        [0.8007, 0.6629, 0.3164, 0.5513, 0.8232, 0.1953],
        [0.7149, 0.6273, 0.4255, 0.4491, 0.9695, 0.1452]])
tensor([[0.4095, 0.3251],
        [0.8007, 0.6629],
        [0.7149, 0.6273]])
tensor([[0.1432, 0.3541],
        [0.3164, 0.5513],
        [0.4255, 0.4491]])
tensor([[0.3867, 0.2708],
        [0.8232, 0.1953],
        [0.9695, 0.1452]])


split : chunck와 동일하난 기즌이 다름(텐서의 크기는 몇으로 나눌꺼냐?)

In [60]:
tensor = torch.rand(3, 6)
t1, t2 = torch.split(tensor, 3, dim = 1)
print(t1)
print(t2)

tensor([[0.7322, 0.6341, 0.5540],
        [0.8146, 0.8972, 0.9548],
        [0.3210, 0.4938, 0.3534]])
tensor([[0.4683, 0.8673, 0.4003],
        [0.0215, 0.1633, 0.5194],
        [0.4954, 0.4701, 0.1539]])


# Torch <==> Numpy

Torch Tensor를 Numpy array로 변환 가능
- numpy()
- from_numpy()

Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유 함으로 하나가 변하면 다른 하나도 변함

In [64]:
a = torch.ones(2,4)
print(a)

b = a.numpy()
print(b)

a.add_(3)

print(a)
print(b)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.]])
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [66]:
a = np.ones(7)
b = torch.from_numpy(a)

np.add(a, 1, out = a)

print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
