In [1]:
# !pip3 install torch
# !pip3 install torchvision
# !pip3 install matplotlib
# !pip3 install torchmetrics

import numpy as np
import torch
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision
from torchvision import datasets
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
print("Success")

Success


In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [4]:
w = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# hypothesis = 1 / (1+ torch.exp(-(x_train.matmul(w) + b)))
hypothesis = torch.sigmoid(x_train.matmul(w) + b)

print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


In [5]:
# losses = -(y_train * torch.log(hypothesis) + (1-y_train)*torch.log(1 - hypothesis))
# cost = losses.mean()
cost = F.binary_cross_entropy(hypothesis, y_train)

print(cost)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)


In [12]:
w = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w,b], lr= 1)

for epoch in range(1, 1001):

  hypothesis = torch.sigmoid(x_train.matmul(w) + b) # 활성화 함수 통과 = 모델의 output
  cost = F.binary_cross_entropy(hypothesis, y_train) # Loss 함수

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(f"Epoch :{epoch}/1000, Loss : {cost.item()}")

Epoch :100/1000, Loss : 0.13564400374889374
Epoch :200/1000, Loss : 0.08096420019865036
Epoch :300/1000, Loss : 0.05806247889995575
Epoch :400/1000, Loss : 0.045398008078336716
Epoch :500/1000, Loss : 0.03732698783278465
Epoch :600/1000, Loss : 0.031719982624053955
Epoch :700/1000, Loss : 0.027591736987233162
Epoch :800/1000, Loss : 0.02442231960594654
Epoch :900/1000, Loss : 0.021910781040787697
Epoch :1000/1000, Loss : 0.019870633259415627


In [17]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

x_test = torch.FloatTensor(x_data)
y_test = torch.FloatTensor(y_data)

hypothesis = torch.sigmoid(x_test.matmul(w) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
prediction = prediction.type(torch.IntTensor)
correct_prdeiction = prediction == y_test

print(hypothesis)
print(prediction)
print(correct_prdeiction)

tensor([[2.7711e-04],
        [3.1636e-02],
        [3.9014e-02],
        [9.5618e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)
tensor([[0],
        [0],
        [0],
        [1],
        [1],
        [1]], dtype=torch.int32)
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])


In [30]:
class BinaryClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2,1) # M x 8 차원의 입렬과 1개의 Bias
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    return self.sigmoid(self.linear(x))


def calculate_acc(output, label):
  predict = output >= torch.FloatTensor([0.5])
  predict = predict.type(torch.IntTensor)

  acc = (predict == label).type(torch.IntTensor)
  acc = torch.sum(acc)

  return acc

x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


model = BinaryClassifier()
optimizer = optim.SGD(model.parameters(), lr = 1)

total_epoch = 100

for epoch in range(1, total_epoch+1):

  output = model(x_train)
  loss = F.binary_cross_entropy(output, y_train)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 10 == 0:
    print(f"Epoch : {epoch}/{total_epoch}, Loss : {loss.item()}, Acc : {calculate_acc(output, y_train) / len(y_train) * 100} ")



Epoch : 10/100, Loss : 0.7173536419868469, Acc : 66.66667175292969 
Epoch : 20/100, Loss : 0.5567989945411682, Acc : 83.33332824707031 
Epoch : 30/100, Loss : 0.4413827657699585, Acc : 83.33332824707031 
Epoch : 40/100, Loss : 0.35664287209510803, Acc : 83.33332824707031 
Epoch : 50/100, Loss : 0.2784411609172821, Acc : 83.33332824707031 
Epoch : 60/100, Loss : 0.21237830817699432, Acc : 83.33332824707031 
Epoch : 70/100, Loss : 0.16953444480895996, Acc : 100.0 
Epoch : 80/100, Loss : 0.15006159245967865, Acc : 100.0 
Epoch : 90/100, Loss : 0.1390935331583023, Acc : 100.0 
Epoch : 100/100, Loss : 0.12997306883335114, Acc : 100.0 
