In [2]:
# !pip3 install torch
# !pip3 install torchvision
# !pip3 install matplotlib
# !pip3 install torchmetrics

import numpy as np
import torch
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision
from torchvision import datasets
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
print("Success")

Success


In [8]:
t1 = torch.FloatTensor([[3,3]])
t2 = torch.FloatTensor([[2,2]])

print(t1 + t2)

print(t1 + torch.Tensor([100])) # 100 -> [[100, 100]]

m1 = torch.Tensor([[1,2]])     # [[1,2]] -> [[1,2], [1,2]] 
m2 = torch.Tensor([[3], [4]])  # [[3],[4]] -> [[3,3],[4,4]] # 두 행렬을 더큰 차원으로 바꿔서 연산을 수행한다.

print(m1 + m2)


tensor([[5., 5.]])
tensor([[103., 103.]])
tensor([[4., 5.],
        [5., 6.]])


- 일반적인 곱(*)을 사용하면 자동으로 차원을 변경하여 각각 원소별 곱을 수행한다.
- Multiplication은 일반적인 행렬의 곱 연산을 수행한다.

In [11]:
m1 = torch.Tensor([[1,2],[3,4]])     
m2 = torch.Tensor([[1], [2]])
print(m1.matmul(m2))

print(m1*m2)


tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


- mean() 함수는 LongTensor에 대해서 수행하지 못한다.

In [19]:
t1 = torch.Tensor([[1,2],[3,4]])
t2 = torch.LongTensor([1,2])

print(t1.mean()) # 전체 원소에 대해 평균 수행
# print(t2.mean())

print("====== Mean ======")
print(t1.mean(dim = 0)) # row에 대해 평균 수행
print(t1.mean(dim = 1)) # col에 대해 평균 수행

print("====== Sum ======")
print(t1.sum())
print(t1.sum(dim = 0))
print(t1.sum(dim = 1))

print("====== Max ======")
print(t1.max())
print(t1.max(dim = 0))
print(t1.max(dim = 1))


tensor(2.5000)
====== Mean ======
tensor([2., 3.])
tensor([1.5000, 3.5000])
====== Sum ======
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
====== Max ======
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


- View 는 numpy의 Reshape 함수 이다.

In [26]:
t = np.array([[[0,1,2],
               [3,4,5]],
               [[10,11,12],
               [13,14,15]]])

ft = torch.Tensor(t)
print(ft.shape)

print(ft.view(-1, 3).shape)
print(ft.view(2, 1, -1).shape) # view 내부 원소 합이 기존 데이터 shape의 곱과 같으면 된다.

torch.Size([2, 2, 3])
torch.Size([4, 3])
torch.Size([2, 1, 6])


- Squeeze 를 통해 dim 이 1인 차원을 없앨 수 있다.
- Unsqueeze를 통해 dim 이 1인 차원을 추가 한다.

In [30]:
t = np.array([[0],[1],[2]])
ft = torch.Tensor(t)

print(ft.shape)
print(ft.squeeze().shape) # 1인 차원을 없애 준다.
print(ft.unsqueeze(dim=0).shape) # 1인 차원을 추가 한다.


torch.Size([3, 1])
torch.Size([3])
torch.Size([1, 3, 1])


Type Casting

In [32]:
lt = torch.LongTensor([1,2,3,4,])
print(lt)
print(lt.float())
bt = (lt == 3)
print(bt) # 조건 문을 토앻 byteTensor를 생성할 수 있다.

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([False, False,  True, False])


- Concatenate 두 텐서 합치기

In [34]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[11,12],[13,14]])

print(torch.cat([x,y], dim = 0)) # row 쪽으로 추가
print(torch.cat([x,y], dim = 1)) # col 쪽으로 추가

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [11., 12.],
        [13., 14.]])
tensor([[ 1.,  2., 11., 12.],
        [ 3.,  4., 13., 14.]])


Stacking

In [37]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[11,12],[13,14]])
z = torch.Tensor([[111,12],[113,114]])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z]).shape) # 차원이 새로 추가 된다. 리스트를 만든것

tensor([[[  1.,   2.],
         [  3.,   4.]],

        [[ 11.,  12.],
         [ 13.,  14.]],

        [[111.,  12.],
         [113., 114.]]])
torch.Size([3, 2, 2])


In [42]:
x = torch.Tensor([1,2,3,4]).cuda()

print(torch.ones_like(x)) # device도 같다.
print(torch.zeros_like(x))
print(torch.ones([2,2]))
print(torch.zeros([2,2]))

tensor([1., 1., 1., 1.], device='cuda:0')
tensor([0., 0., 0., 0.], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [43]:
x = torch.Tensor([1,2,3,4]).cuda()
print(x)

x.mul_(2)

print(x)

tensor([1., 2., 3., 4.], device='cuda:0')
tensor([2., 4., 6., 8.], device='cuda:0')
